version: "3.1"

volumes:
  code-data:
  db-data:
  solr-data:
  postgres-data:

networks:
  net:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.5
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/mysql
      - ./shared:/srv/shared
    ports:
      - "3306:3306"
    networks:
      - net

  php:
    build:
      context: ./conf
      dockerfile: Dockerfile-php-apache
    container_name: "${PROJECT_NAME}_php"
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net
    volumes:
      #Configuration for Apache and html folder to share projects
      - ./conf/php/git_user_initialize.sh:/home/docker/git_user_initialize.sh
      - ./conf/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php_extended.ini
      - ./logs:/var/log/apache2/docker
      - ./html:/var/www/html:delegated
      - ./shared:/srv/shared

  solr:
    image: solr:8.0
    container_name: "${PROJECT_NAME}_solr"
    networks:
      - net
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
      - ./shared:/srv/shared
    command:
      - solr-precreate
      - drupalsolr

